#!/bin/bash
# EC2 user_data bootstrap script — runs once on first launch.
#
# Installs Docker, Docker Compose plugin, and clones the repository so the
# deploy.yml workflow can run `docker compose up -d` on subsequent pushes.
#
# This script is passed to the EC2 instance via `user_data` in compute.tf.
# To debug: check /var/log/cloud-init-output.log on the instance.
#
# Prerequisites on the instance after this runs:
#   - Docker and Docker Compose v2 available as `docker compose`
#   - Repo cloned at /opt/myproject (deploy.yml does `git pull` on each deploy)
#   - ec2-user added to the `docker` group (no sudo needed for Docker commands)

set -euo pipefail

# ---------------------------------------------------------------------------
# System update
# ---------------------------------------------------------------------------
yum update -y

# ---------------------------------------------------------------------------
# Docker installation (Amazon Linux 2023)
# ---------------------------------------------------------------------------
yum install -y docker git

# Enable and start the Docker daemon
systemctl enable docker
systemctl start docker

# Add ec2-user to the docker group so deploy.yml SSH commands don't need sudo
usermod -aG docker ec2-user

# ---------------------------------------------------------------------------
# Docker Compose v2 plugin
# ---------------------------------------------------------------------------
# Amazon Linux 2023 provides docker-compose-plugin via the default repos
yum install -y docker-compose-plugin

# Verify installation
docker compose version

# ---------------------------------------------------------------------------
# Clone the repository
# ---------------------------------------------------------------------------
# The SSH deploy key must be set up on the instance for this to work.
# Alternatively, use HTTPS with a fine-grained GitHub token.
mkdir -p /opt/myproject
cd /opt/myproject

# Clone on first boot — deploy.yml will `git pull` on subsequent deploys
if [ ! -d ".git" ]; then
  # Replace with your repo URL
  git clone https://github.com/myorg/v1-mono.git .
fi

# ---------------------------------------------------------------------------
# Create environment file placeholder
# ---------------------------------------------------------------------------
# The actual values are set as GitHub Actions secrets and written by deploy.yml,
# or managed via AWS Secrets Manager in a more advanced setup.
if [ ! -f "/opt/myproject/.docker/production/.env" ]; then
  cat > /opt/myproject/.docker/production/.env << 'EOF'
# Generated by user_data.sh — replace with real values
# Alternatively, set these as system environment variables or use AWS Secrets Manager
SECRET_KEY=changeme
POSTGRES_DB=myproject
POSTGRES_USER=myproject
POSTGRES_PASSWORD=changeme
DOMAIN=api.example.com
VERCEL_DOMAIN=myapp.vercel.app
AWS_S3_BUCKET_NAME=myproject-production-media
AWS_S3_REGION_NAME=eu-west-1
ACME_EMAIL=ops@example.com
EOF
fi

echo "[user_data] Bootstrap complete."
